// 风扇配置
export const fanConfig = (t) => [
  {
    id: 'power',
    type: 'POWER_STATUS_ON',
    title: t('pages.ir.remote.power'),
    position: { row: 0, col: 0 },
    clickable: true,
  },
  {
    id: 'mode',
    type: 'MODE',
    title: t('pages.ir.remote.mode'),
    position: { row: 0, col: 1 },
    clickable: true,
  },
  {
    id: 'shake_head',
    type: 'SHAKE_HEAD',
    title: t('pages.ir.remote.headShake'),
    position: { row: 0, col: 2 },
    clickable: true,
  },
  {
    id: 'low',
    type: 'LOW',
    title: t('pages.ir.remote.lowSpeed'),
    position: { row: 1, col: 0 },
    clickable: true,
  },
  {
    id: 'middle',
    type: 'MIDDLE',
    title: t('pages.ir.remote.mediumSpeed'),
    position: { row: 1, col: 1 },
    clickable: true,
  },
  {
    id: 'high',
    type: 'HIGH',
    title: t('pages.ir.remote.highSpeed'),
    position: { row: 1, col: 2 },
    clickable: true,
  },
  {
    id: 'fan_speed',
    type: 'FAN_SPEED',
    title: t('pages.ir.remote.fanSpeed'),
    position: { row: 2, col: 0 },
    clickable: true,
  },
];

// 灯光配置
export const lightConfig = (t) => [
  {
    id: 'power_on',
    type: 'POWER_STATUS_ON',
    title: t('pages.ir.remote.openLight'),
    position: { row: 0, col: 0 },
    clickable: true,
  },
  {
    id: 'mode',
    type: 'MODE',
    title: t('pages.ir.remote.mode'),
    position: { row: 0, col: 1 },
    clickable: true,
  },
  {
    id: 'power_off',
    type: 'POWER_STATUS_OFF',
    title: t('pages.ir.remote.closeLight'),
    position: { row: 0, col: 2 },
    clickable: true,
  },
  {
    id: 'brightness_up',
    type: 'BRIGHTNESS_UP',
    title: t('pages.ir.remote.brightnessUp'),
    position: { row: 1, col: 0 },
    clickable: true,
  },
  {
    id: 'brightness_down',
    type: 'BRIGHTNESS_DOWN',
    title: t('pages.ir.remote.brightnessDown'),
    position: { row: 1, col: 1 },
    clickable: true,
  },
  {
    id: 'color_temp_up',
    type: 'COLOR_TEMP_UP',
    title: t('pages.ir.remote.colorTempUp'),
    position: { row: 1, col: 2 },
    clickable: true,
  },
  {
    id: 'color_temp_down',
    type: 'COLOR_TEMP_DOWN',
    title: t('pages.ir.remote.colorTempDown'),
    position: { row: 2, col: 0 },
    clickable: true,
  },
];

// 电视配置
export const tvConfig = (t) => [
  {
    id: 'power',
    type: 'POWER_STATUS_ON',
    title: t('pages.ir.remote.power'),
    position: { row: 0, col: 0 },
    clickable: true,
  },
  {
    id: 'home',
    type: 'HOME',
    title: t('pages.ir.remote.home'),
    position: { row: 0, col: 1 },
    clickable: true,
  },
  {
    id: 'back',
    type: 'BACK',
    title: t('pages.ir.remote.back'),
    position: { row: 0, col: 2 },
    clickable: true,
  },
  {
    id: 'mute',
    type: 'MUTE',
    title: t('pages.ir.remote.mute'),
    position: { row: 1, col: 0 },
    clickable: true,
  },
  {
    id: 'up',
    type: 'UP',
    title: t('pages.ir.remote.up'),
    position: { row: 1, col: 1 },
    clickable: true,
  },
  {
    id: 'menu',
    type: 'MENU',
    title: t('pages.ir.remote.menu'),
    position: { row: 1, col: 2 },
    clickable: true,
  },
  {
    id: 'left',
    type: 'LEFT',
    title: t('pages.ir.remote.left'),
    position: { row: 2, col: 0 },
    clickable: true,
  },
  {
    id: 'ok',
    type: 'OK',
    title: t('pages.ir.remote.ok'),
    position: { row: 2, col: 1 },
    clickable: true,
  },
  {
    id: 'right',
    type: 'RIGHT',
    title: t('pages.ir.remote.right'),
    position: { row: 2, col: 2 },
    clickable: true,
  },
  {
    id: 'volume_up',
    type: 'VOLUME_UP',
    title: t('pages.ir.remote.volumeUp'),
    position: { row: 3, col: 0 },
    clickable: true,
  },
  {
    id: 'down',
    type: 'DOWN',
    title: t('pages.ir.remote.down'),
    position: { row: 3, col: 1 },
    clickable: true,
  },
  {
    id: 'channel_up',
    type: 'CHANNEL_UP',
    title: t('pages.ir.remote.channelUp'),
    position: { row: 3, col: 2 },
    clickable: true,
  },
  {
    id: 'volume_down',
    type: 'VOLUME_DOWN',
    title: t('pages.ir.remote.volumeDown'),
    position: { row: 4, col: 0 },
    clickable: true,
  },
  {
    id: 'channel_down',
    type: 'CHANNEL_DOWN',
    title: t('pages.ir.remote.channelDown'),
    position: { row: 4, col: 1 },
    clickable: true,
  },
];
